[server]
address = "127.0.0.1"
port = 8590
headless = true
enableCORS = false
enableXsrfProtection = true

[theme]
# Frequenz-inspired brand palette (adjust if you have official hex codes)
primaryColor = "#00AEEF"            # Primary accent
backgroundColor = "#FFFFFF"         # App background
secondaryBackgroundColor = "#F1F5F9" # Sidebar/panels
textColor = "#0B1221"               # Primary text
font = "sans serif"
