[server]
address = "127.0.0.1"
port = 8590
headless = true
enableCORS = false
enableXsrfProtection = true

[theme]
base = "dark"
primaryColor = "#62B5B1"
backgroundColor = "#2D1726"
secondaryBackgroundColor = "#556372"
textColor = "#E6EAEB"
font = "sans serif"
