[server]
address = "127.0.0.1"
port = 8590
headless = true
enableCORS = false
enableXsrfProtection = true

[theme]
# Frequenz-inspired dark theme based on sampled logo colors
# Primary accent sampled ≈ #10D0B0
primaryColor = "#10D0B0"
# Dark background akin to site hero
backgroundColor = "#0B1221"
secondaryBackgroundColor = "#16202F"
textColor = "#E6F4F1"
font = "sans serif"
